### ISSUE TITLE
文章页显示Database Query Error

### ISSUE THREAD

**Issue by ASuzuhA** [Seevil/cactus#35]

**Comment by ASuzuhA** [comment]
SQLSTATE[HY000]: General error: 1 no such function: now
Typecho_Db_Query_Exception: SQLSTATE[HY000]: General error: 1 no such function: now in /app/var/Typecho/Db/Adapter/Pdo.php:105
Stack trace:
#0 /app/var/Typecho/Db.php(368): Typecho_Db_Adapter_Pdo->query('SELECT *  FROM ...', Object(PDO), 1, 'SELECT', 'typecho_content...')
#1 /app/var/Typecho/Db.php(398): Typecho_Db->query(Object(Typecho_Db_Query), 1)
#2 /data/themes/cactus-master/functions.php(134): Typecho_Db->fetchAll(Object(Typecho_Db_Query))
#3 /data/themes/cactus-master/post.php(116): theme_random_posts()
#4 /app/var/Widget/Archive.php(2031): require_once('/data/themes/ca...')
#5 /app/var/Typecho/Router.php(138): Widget_Archive->render()
#6 /app/index.php(23): Typecho_Router::dispatch()
#7 {main}

**Comment by Seevil** [comment]
你用的是什么数据库

**Comment by ASuzuhA** [comment]
pdo_SQLite  :D

**Comment by Seevil** [comment]
之前代码有做SQLite兼容的，你typecho什么版本啊

**Comment by ASuzuhA** [comment]
嗯嗯，我这个版本是第三方修改的，作者您做了适配SQLite，那应该是我版本的问题，虽然可惜用不了，但感谢作者回复，谢谢大佬^ω^
